blog/urls.py
from django.conf.urls import url

from blog.views import PostDetailView, PostListView, PostCreateView

urlpatterns = [
    url('^$', PostListView.as_view(), name='post-list'),
    url('^(?P<pk>\d+)/$', PostDetailView.as_view(), name='post-detail'),
    url('^new/$', PostCreateView.as_view(), name='post-new')
]

dablog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^blog/', include('blog.urls', namespace='blog'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.core.urlresolvers import reverse


class Post(models.Model):
    author = models.ForeignKey('auth.User', related_name='posts')
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    published = models.DateTimeField()
    intro = models.CharField(max_length=255)
    content = models.TextField()
    content_rst = models.TextField()
    #TODO: add file field for Plain text files (support for RST, Markdown, and Latex)
    # 1. rst files will be read, meta data will be parsed to populate other Post fields
    # 2. rst file will be updated to include meta data on the Post object in the database
    #
    # This will allow for plain text ReStructuredText representations of Post objects.
    # Maintaining RST files (potentially version controlled) will allow other
    # colaberators to submit edits to blog posts via Github.
    #
    # TODO: figure out how images and files embended inside RST files should be
    # stored in the database (base64 encode them?)
    class Meta:
        ordering = ['published', 'title']

    def save(self, *args, **kwargs):
        if not self.id:
            self.published = timezone.now()
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        # TODO: include slug
        return reverse('blog:post-detail', kwargs={'pk': self.id})

    def __str__(self):
        return u'{}'.format(self.slug)

blog/views.py
from rest_framework import renderers, generics
from rest_framework.response import Response
from blog.models import Post
from blog.serializer import PostSerializer


class PostListView(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    renderer_classes = [
        renderers.TemplateHTMLRenderer,
        renderers.AdminRenderer,
        renderers.JSONRenderer,
    ]

    def get(self, request, *args, **kwargs):
        posts = self.get_queryset().order_by('-published')
        return Response({'posts': posts}, template_name='post_list.html')


class PostDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    template_name = 'post_detail.html'
    renderer_classes = [
        renderers.TemplateHTMLRenderer,
        renderers.AdminRenderer,
        renderers.JSONRenderer
    ]


class PostCreateView(generics.CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    template_name = 'post_new.html'
    renderer_classes = [
        renderers.TemplateHTMLRenderer,
        renderers.AdminRenderer,
        renderers.JSONRenderer
    ]

    def get(self, request, *args, **kwargs):
        return Response({'serializer': self.serializer_class})

blog/templates/base.html
<!doctype html>
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="Tom Leo's Website">
    <meta name="author" content="Tom Leo">
    <title>Website of Tom Leo</title>
    {% endblock %}
    {% block styles %}{% endblock %}
</head>
<body>
    <header>
        <h1>TomLeo.com</h1>
        {% block nav %}
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'blog:post-list' %}">Blog</a></li>
            </ul>
        </nav>
        {% endblock %}
        {% if request.user.is_superuser %}
        <div class="o-admin-tools">
        <ul>
            <li>
                <a href="{% url 'blog:post-new' %}">New Post</a>
            </li>
        </ul>
        </div>
        {% endif %}
    </header>
    <main>
    {% block main %}{% endblock %}
    </main>
    <footer>
        TomLeo.com &copy; 2007–2017
    </footer>
</body>

blog/templates/post_detail.html
{% extend 'base.html' %}
{% block main %}
<article itemscope itemtype="http://schema.org/BlogPosting">
    <header>
        <h1>{{ title }}</h1>
        <time class="dtstart" datetime="2011-10-05T09:00Z">9am on October 5</time>
    </header>
    {{ intro }}
    <div itemprop="articleBody">
        {{ content }}
    </div>
    <footer>
        <div class="a-published">
            Published <data itemprop="datePublished" value="2011-11-03"></data>
        </div>
        <div class="a-author">
            By <span itemprop="author">{{ author }}</span>
        </div>
    </footer>
</article>
{% endblock %}

blog/templates/post_list.html
{% extends 'base.html' %}
{% block main %}
<nav>
    <ul>
        {% for post in posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </li>
        {% endfor %}
    </ul>
</nav>
{% endblock %}

blog/templates/post_new.html
{% extends 'base.html' %}
{% load rest_framework %}
{% block main %}
<h1>Post New</h1>

<form action="{% url 'blog:post-new' %}" method="post">
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" name="submit">
</form>
{% endblock %}

templates/index.html
<h1>Test</h1>